version: "3.9"
services:
  server:
    build: .
    container_name: allbooks-frontend
    image: brunojose1977/exercicio11-allbooks-docker-compose-frontend:1.2.0
    ports:
      - 8080:3000  #Reacj.js
      - 5000:80    #NGINX
